language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PINS="dockerfile-cmd.dev:. dockerfile.dev:. dockerfile-opam.dev:."
 matrix:
   - OCAML_VERSION=4.06 DISTRO=debian-stable PACKAGE=dockerfile
   - OCAML_VERSION=4.06 DISTRO=debian-stable PACKAGE=dockerfile-opam
   - OCAML_VERSION=4.06 DISTRO=debian-stable PACKAGE=dockerfile-cmd
   - OCAML_VERSION=4.08 DISTRO=ubuntu PACKAGE=dockerfile-cmd
   - OCAML_VERSION=4.08 DISTRO=alpine PACKAGE=dockerfile-cmd
   - OCAML_VERSION=4.09 DISTRO=ubuntu PACKAGE=dockerfile-cmd
   - OCAML_VERSION=4.09 DISTRO=alpine PACKAGE=dockerfile-cmd
